config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  resource :static_pages, only: %i[top]

  get 'login', to: 'user_sessions#new', :as => :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :how_to_plays, only: %i[index]
  resource :profiles, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update new]

  resources :users, only: %i[new create]

  resources :boards do
    resource :like, only: %i[create destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  paginates_per 6
  belongs_to :user
  belongs_to :subject

  has_many :liking_users, through: :likes, source: :user

  validates :conclusion, presence: true, length: { maximum: 255 }
  validates :runner_up, presence: true, length: { maximum: 255 }

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :boards
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :boards

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  def own?(object)
    id == object&.user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, danger: t('flash.no_user')
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: %i[edit update destroy]
  before_action :require_login, only: [:new, :create]
  skip_before_action :require_login, only: [:index, :show]

  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])

  end

  def new
    title = params[:title]
    @subject = Subject.find_or_create_by(title: title)
    @board = Board.new(subject: @subject)
  end

  def show
    @board = Board.find(params[:id])
    @subject = Subject.find(@board.subject_id)
    @user_name = @board.user.name
  end

  def create
    @subject = Subject.find_or_create_by(title: params[:title])
    @board = current_user.boards.build(board_params)
    @board.subject = @subject
    if @board.save
      redirect_to boards_path, success: t('flash.board_success')

    else
      flash.now[:danger] = t('flash.board_fault')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @subject = @board.subject
  end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), success: t('defaults.flash_message.updated', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_updated', item: Board.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board.destroy!
    redirect_to boards_path, success: t('defaults.flash_message.deleted', item: Board.model_name.human), status: :see_other
  end

  def likes
    @q = current_user.bookmark_boards.ransack(params[:q])
    @like_boards = @q.result(distinct: true).includes(:user).page(params[:page]).order(created_at: :desc)
  end

  private

  def find_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:conclusion, :runner_up, :subject_id)
  end
end

app/controllers/how_to_plays_controller.rb
class HowToPlaysController < ApplicationController
  skip_before_action :require_login
  def index; end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login

  def new;
  end

  def create
    @user = User.find_by(email: params[:email])
    @user&.deliver_reset_password_instructions!
    #公式ドキュメントにはこのコードに [if @user]を付けており、バリデーションを出来るようにしているが
    # 「存在しないメールアドレスです」という旨の文言を表示すると、逆に存在するメールアドレスを特定されてしまうため、
    # あえて成功時のメッセージを送信させている
    redirect_to login_path, success: t('.success')
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    return not_authenticated if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password(params[:user][:password])
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit, status: :unprocessable_entity
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profiles_path, success: t('defaults.flash_message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.flash_message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] = t('flash.login_success')
      redirect_to boards_path
    else
      flash[:danger] = t('flash.login_fault')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:success] = t('flash.logout')
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('flash.user_success')
      redirect_to root_path
    else
      flash[:danger] = t('flash.user_fault')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :salt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/how_to_plays_helper.rb
module HowToPlaysHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="card">
      <div class="card-body">
        <div class="d-flex"></div>
          <h4 class="card-title">
            <%= link_to board.subject.title, board_path(board) %>
          </h4>
        <p class="card-text">
          <%= "投稿者： #{board.user.name}" %>
        </p>
        <p class="card-text">
          <%= "優勝：#{board.conclusion}" %>
        </p>
        <p class="card-text">
          <%= "次点：#{board.runner_up}" %>
        </p>
          <% if current_user&.own?(board) %>
            <div class='ms-auto d-flex justify-content-end'>
              <%= link_to edit_board_path(board), id: "button-edit-#{board.id}", style: "margin-right: 10px;"  do %>
                <p> 編集 </p>
              <% end %>
              <br>
              <%= link_to board_path(board), id: "button-delete-#{board.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                <p> 削除 </p>
              <% end %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="mb-3">
    <%= f.label :title, class: "board_title" %>
      <%= text_field_tag :title, @subject.title, class: "form-control", id: "board_title", readonly: true %>
    </div>
    <div class="mb-3">
      <%= f.label :conclusion, class: "board_conclusion" %>
      <%= f.text_field :conclusion, class: "form-control", id: "board_conclusion", rows: 10 %>
    </div>
    <div class="mb-3">
      <%= f.label :runner_up, class: "board_runner_up" %>
      <%= f.text_field :runner_up, class: "form-control", id: "board_runner_up", rows: 10 %>
    </div>
  <%= f.submit (board.new_record? ? I18n.t('submit.create') : I18n.t('submit.update')), class: "btn btn-primary" %>
<% end %>

app/views/boards/_search_form.erb
<%= search_form_for q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_or_body_cont, class: "form-control", plaeholder: t('defaults.search_word') %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      </div>
  </div>
<% end %>

app/views/boards/edit.html.erb
<% content_for(:title, '掲示板編集 | 空想ディベート') %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title')%></h1>
      <%= render 'form', board: @board%>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<% content_for(:title, '掲示板一覧 | 空想ディベート')%>
<div class="container pt-3">

  <h2><%= t('.title')%></h2>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render partial: 'board', collection: @boards %>
        <% else %>
          <div class="mb-3">掲示板がありません</div>
        <% end %>
        <%= paginate @boards, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<% content_for(:title, '掲示板作成 | 空想ディベート') %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title')%></h1>
      <%= render 'form', board: @board %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for(:title, "#{@subject.title} | 空想ディベート") %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <article class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-9">
              <h3 style="display: inline;"><%= @subject.title %></h3>
            </div>
          </div>
        <p class="card-text">
          <%= "投稿者： #{@board.user.name}" %>
        </p>
        <p class="card-text">
          <%= "優勝：#{@board.conclusion}" %>
        </p>
        <p class="card-text">
          <%= "次点：#{@board.runner_up}" %>
        </p>
        </div>
      </article>
      </div>
    </div>
  </div>
</div>

app/views/how_to_plays/_how_to.html.erb
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        <h3>BOTの導入方法</h3>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse">
      <div class="accordion-body">
        画面上部にある【ディスコードBOTを追加】を押して頂く事でサーバー追加画面が開きます<br>
        BOTの追加には管理者権限が必要です。<br>
        既にサーバーを作成済みの場合＝＞<br>
        ディスコードでサーバーを作った方であれば自動的に付与されている為、そのまま追加の操作をして下さい<br>
        <br>
        サーバーを未作成の場合＝＞<br>
        これはディスコード側での操作が必要となりますので、<br>
        作り方が分からない場合『ディスコード　サーバーの建て方』など検索し作成してからご利用下さい。
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        <h3>遊び方</h3>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
      <div class="accordion-body">
        (簡単な操作動画を添付)<br>
        動画のように『/ping』とコマンドを打って頂くと、自動的にBOTが議題を合成し出題してくれます。<br>
        そちらを元に議論を交わして頂くと、一定時間経過後BOTから議論時間終了のアナウンスが行われます。<br>
        その際にURLを提示されるため、そこから投稿ページへ移動して頂き議論結果を投稿し共有して下さい。
      </div>
    </div>
  </div>
    </div>
  </div>
</div>

app/views/how_to_plays/index.html.erb
<% content_for(:title, " | RUNTEQ BOARD APP") %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= "遊び方"%></h1>

<div>

  <%# <video autoplay muted loop width="500" height="350" src="/assets/videos/discord_start.mp4" controls ></video> %>

</div>
<div>
  <%= render 'how_to' %>
</div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "空想ディベート" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/flash_message'%>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @user, url: password_reset_path(@token), method: :patch do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %><br>
          <%= @user.email %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title') %></h1>
      <%= form_with url: password_resets_path do |f| %>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1 class="float-left mb-5"><%= t('.title') %></h1>
      <%= link_to t('defaults.edit'), edit_profiles_path, class: 'btn btn-success float-right' %>
      <table class="table">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:full_name) %></th>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:email) %></th>
          <td><%= current_user.email %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
    <%= link_to "空想ディベート掲示板", '/', class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <%= link_to "遊び方", how_to_plays_path, class: "navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "ディスコードBOTを追加", 'https://discord.com/api/oauth2/authorize?client_id=1174339961194041344&permissions=8&scope=bot', class: "navbar-brand"%>
          </li>
        </ul>
          <li class="nav-item">
            <%= link_to "掲示板", boards_path, class: "navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "会員登録", new_user_path, class: "navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", login_path, class: "navbar-brand"%>
          </li>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.present? && object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
    <%= link_to "空想ディベート掲示板", '/', class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <%= link_to "遊び方", how_to_plays_path, class: "navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "ディスコードBOTを追加", 'https://discord.com/api/oauth2/authorize?client_id=1174339961194041344&permissions=8&scope=bot', class: "navbar-brand"%>
          </li>
        </ul>
          <li class="nav-item">
            <%= link_to "掲示板", boards_path, class: "navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", profiles_path, class: "navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", '/logout', class: "navbar-brand", data: { turbo_method: :delete }%>
          </li>
      </div>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

<main>

<div class="center-block">
    <hr class="featurette-divider">
  <h1>「君って『一番可愛い【飲み物】』ってなんだと思う？」</h1>
  <div style="text-align: center;">
    <%= image_tag('top.jpeg'  ) %>
  </div>
</div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->




  <div class="container marketing">


      <div class="container-top">
      <hr class="featurette-divider">
    <div class="custom-bg-color">
    <h4 style="text-align: center;">ディベートはお堅い会話ばっかり・・・</h4>
    <h4 style="text-align: center;">言い合いになってなんだか怖そう・・・</h4>
    <h4 style="text-align: center;">そう思いがちなディベートを、カジュアルに遊んでみませんか？
    <h4 style="text-align: center;">　</h4>
    <h4 style="text-align: center;">  このサイトは通話アプリである【Discord(ディスコード)】を使って</h4>
    <h4 style="text-align: center;">友人や学友、会社の仲間と共に遊び感覚で</h4>
    <h4 style="text-align: center;">ディベートの練習や結果を共有をする事が出来るサイトです</h4>

  </div>


      <div class="container-mid">
    <div class="custom-bg-color">
    <h4 style="text-align: center;">ディスコードさえ入れてあれば、3つのSTEPで簡単に実装！</h4>
    <h4 style="text-align: center;">ディスコードのインストールは<a href="https://discord.com/">【こちら】</a></h4>
    <h4 style="text-align: center;">スマートフォンの方は各端末のストアでインストールをお願いします</h4>

  </div>
      <hr class="featurette-divider">
    <!-- Three columns of text below the carousel -->
    <div class="custom-bg-color">
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <h2 class="fw-normal">1.BOTの導入</h2>
        <p>サイト上部の『ディスコードBOTを追加』を<br>クリックすると導入ページに飛びます<br>※導入にはサーバーの管理権限が必要です</p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <h2 class="fw-normal">2.BOTを使ってディベート</h2>
        <p>ディスコードに追加したBOTを使って、<br>提示された議題を元にディベートをして下さい。<br>詳しい導入方法、遊び方は<a href="<%= how_to_plays_url %>">遊び方</a>をご確認下さい</p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <h2 class="fw-normal">3.ディベート結果を投稿</h2>
        <p>ディベート時間が経過したのち<br>BOTからURLを提示されるので、<br>そちらから投稿ページへ行き<br>色んな人にディベート結果を共有しましょう！</p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
    </div>

    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->
</main>
</html>

app/views/user_sessions/new.html.erb
<% content_for(:title, "ログイン | RUNTEQ BOARD APP") %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title')%></h1>
      <%= render 'form' %>
      <div class='text-center'>
        <%= link_to t('.to_register_page'), new_user_path %>
        <%= link_to t('.password_forget'), new_password_reset_path %>
      </div>
    </div>
  </div>
</div>